//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EazyLearn.BookStore.CreditCardValidationWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://creditcardvalidation.com/", ConfigurationName="CreditCardValidationWebService.CreditCardValidationSoap")]
    public interface CreditCardValidationSoap {
        
        // CODEGEN: Generating message contract since element name cardnumber from namespace http://creditcardvalidation.com/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://creditcardvalidation.com/ValidateCreditCard", ReplyAction="*")]
        EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse ValidateCreditCard(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://creditcardvalidation.com/ValidateCreditCard", ReplyAction="*")]
        System.Threading.Tasks.Task<EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse> ValidateCreditCardAsync(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCreditCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCreditCard", Namespace="http://creditcardvalidation.com/", Order=0)]
        public EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequestBody Body;
        
        public ValidateCreditCardRequest() {
        }
        
        public ValidateCreditCardRequest(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://creditcardvalidation.com/")]
    public partial class ValidateCreditCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cardnumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string month;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string year;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string cvv;
        
        public ValidateCreditCardRequestBody() {
        }
        
        public ValidateCreditCardRequestBody(string cardnumber, string month, string year, string cvv) {
            this.cardnumber = cardnumber;
            this.month = month;
            this.year = year;
            this.cvv = cvv;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidateCreditCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidateCreditCardResponse", Namespace="http://creditcardvalidation.com/", Order=0)]
        public EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponseBody Body;
        
        public ValidateCreditCardResponse() {
        }
        
        public ValidateCreditCardResponse(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://creditcardvalidation.com/")]
    public partial class ValidateCreditCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ValidateCreditCardResult;
        
        public ValidateCreditCardResponseBody() {
        }
        
        public ValidateCreditCardResponseBody(bool ValidateCreditCardResult) {
            this.ValidateCreditCardResult = ValidateCreditCardResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CreditCardValidationSoapChannel : EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreditCardValidationSoapClient : System.ServiceModel.ClientBase<EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap>, EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap {
        
        public CreditCardValidationSoapClient() {
        }
        
        public CreditCardValidationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CreditCardValidationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardValidationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CreditCardValidationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap.ValidateCreditCard(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest request) {
            return base.Channel.ValidateCreditCard(request);
        }
        
        public bool ValidateCreditCard(string cardnumber, string month, string year, string cvv) {
            EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest inValue = new EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest();
            inValue.Body = new EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequestBody();
            inValue.Body.cardnumber = cardnumber;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.cvv = cvv;
            EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse retVal = ((EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap)(this)).ValidateCreditCard(inValue);
            return retVal.Body.ValidateCreditCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse> EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap.ValidateCreditCardAsync(EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest request) {
            return base.Channel.ValidateCreditCardAsync(request);
        }
        
        public System.Threading.Tasks.Task<EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardResponse> ValidateCreditCardAsync(string cardnumber, string month, string year, string cvv) {
            EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest inValue = new EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequest();
            inValue.Body = new EazyLearn.BookStore.CreditCardValidationWebService.ValidateCreditCardRequestBody();
            inValue.Body.cardnumber = cardnumber;
            inValue.Body.month = month;
            inValue.Body.year = year;
            inValue.Body.cvv = cvv;
            return ((EazyLearn.BookStore.CreditCardValidationWebService.CreditCardValidationSoap)(this)).ValidateCreditCardAsync(inValue);
        }
    }
}
